UberGuidoZ/Flipper-IRDB

README.md
Added detailed installation instructions for infrared remotes.
=> Add Install Instructions

TVs/lodgenet_lrc3220
Standard hotel remote that works with their menus etc on the tv.
=> Lodgenet_lrc3220

ACs/Konwin/Konwin_GD921BCP_4JR.ir, ACs/ProBreeze/ProBreese_PB_F13B_US.ir, Blu-Ray/LG/LG_AKB73775801.ir, Miscellaneous/Arizer/Arizer_XQ2.ir, TVs/Emerson/Emerson_32FNT004.ir, TVs/Insignia/Insignia.ir, TVs/Vizio/Vizio_XRT136.ir
Added remotes for;
Konwin Space Heater
ProBreeze Remote Oscillating Fan
LG BlueRay/Surround Sound
Arizer Extreme Q2 Vaporizer
Emerson TV
Insignia TV
Vizio TV
=> Added New Remotes

Projectors/BenQ/BenQ_W1070.ir, TVs/Hitachi/Hitachi_LE46H508.ir, TVs/Toshiba/Toshiba_43LF421U21.ir
new file:   TVs/Hitachi/Hitachi_LE46H508.ir
new file:   TVs/Toshiba/Toshiba_43LF421U21.ir
new file:   Projectors/BenQ/BenQ_W1070.ir
=> Added new remotes	

Speakers/Edifier/Edifier_R1280T.ir, TVs/Hisense/Hisense_55K3201GUWUS.ir
=> add some remotes

SoundBars/TCL/TCL_TS5010.ir
Added folder TCL to Soundbars and added device TCL TS5010 within
=> Added device TCL TS5010

TVs/Enseo/Enseo.ir
added an Enseo TV remote found in a hotel
=> added Enseo TV (e.g. used in hotel TV systems...)

Miscellaneous/Woozoo/Woozoo_Fan.ir
Adds timer (1,2,4), and breeze buttons.
=> Add Woozoo buttons

Digital_Signs/iiyama/iiyama_LExx40UHS.ir
Added an IR file for an iiyama LE5540UHS display, however it works on everything in the LExx40UHS range (where xx is the display size in inches)
=> Added an iiyama digital sign

TVs/Denver/Denver_LED-3271.ir, TVs/LG/LG_43NANO779PA.ir
LG 43NANO779PA
Denver LED 3271
=> Uploaded files from GalacticWarri0r

Fans/Rowenta/Rowenta_Eole_Infinite.ir, SoundBars/Bose/Bose_Solo_Soundbar.ir
Added Rowenta Eole Infinite Fan
Updated Bose SoundBar Solo (added Mute button)
=> Added remotes

Fans/Daewoo/Daewoo_DDV200.ir
I've tested each button on two separate fans. Everything seems to work OK.
=> Added Daewoo DDV 200 vertical fan

TVs/Bush/BUSH_TV_VL32HDLED.ir, TVs/Telefunken/Telefunken_L55U405B4CW.ir
Updated the button name from SHUFFLE_CH to PREV_CH (it’s correct function)
=> Updated SHUFFLE_CH to PREV_CH

Fans/LeaderPro/LeaderPro_Desk_Fan.ir, SoundBars/Comhear/YARRA3DX.ir, SoundBars/Comhear/YARRA_3DX.ir
Brand is Comhear model seems to be Yarra 3DX, fixed lines being one singular line and uppercased everything and put correct MUTE,POWER VOL etc naming scheme
=> Added Yarra 3DX (Thanks Dag!)

Audio_Receivers/GPX/Gpx_hc221b.ir
Added the GPX HC221B Remote for Home Audio System from Trekeyus
=> Added GPX HC221B (Thanks Trekeyus!)

Fans/Co_Tech/CO_TECH_towerfan.ir
=> Added Co/Tech Tower Fan 366540 (Thanks Jellyfrog!)

SoundBars/Teufel/Teufel_Cinebase.ir, SoundBars/Teufel/Teufel_Cinebase_Soundbar.ir
Added Teufel CiniBase Soundbar
=> Added Teufel Cinibase SB (Thanks spitzbirne32!)

Speakers/Generic_Unknown_Brand/bl-xk01.ir
Created Generic/Unknown Brand dir and added BL-XK01 Bluetooth Speaker with LED Projector.
=> Added BL-XK01 Bluetooth Speaker (Thanks Trekeyus!)

Projectors/Casio/Casio_YT-130.ir
Added a button for "Freeze" to freeze the projector display
=> Add Freeze button to remote

TVs/LG/LG_32LN5406
=> LG_32LN5406

TVs/Medion_MD21302
The "CH-A" at the end is the country code, in other country, it's the same model number, only this last part changing.
=> Medion_MD21302

CD_Players/GPX/GPX_cd_radio.ir, Miscellaneous/iHome/IhomeRz6.ir
Adding the following .ir files:
- GPX CD/Radio remote under `CD_Players`
- iHome iPod player under `Misc`
Both of these come from my repo here: https://github.com/RooneyMcNibNug/Flipper-nil (feel free to yoink any new ones from here)
I changed some of the button names per the main `README`
Let me know if you need anything else here, and thanks for this project.
=> Adding a couple of remotes - CD Player & iHome

TVs/Akai/AKAI_ATE_22Y604W.ir
=> Add one new TV remote

CD_Players/Denon/Denon_RC_1199.ir
Technically more than a CD player, a full mini-hifi stack which also plays DVD, Internet Radio, etc. But closest category I could find in this repo :)
=> Add one Denon CD player remote

Touchscreen_Displays/SMART_Technologies/SMART_Board_MX.ir
=> Add SMART Technologies Board

DVD_Players/Strato/Strato_DVD507.ir, LED_Lighting/Cameo/CLPFLAT1REMOTE.ir, SoundBars/Denon/Denon_RC-1230.ir, TVs/LG/LG_AKB72914048.ir
Camoe is a brand of Adam Hall Group. But in most cases when searching for the remote the only name that is coming up is Cameo.
The remote should also work with the whole CLPFLAT1 and ROOT Series
**Picture of the remote:**
**Picture of the DVD Player:**
**Picture of the Remote:**
**Picture of the TV:**
**Picture of the Remote**
**Picture of the Soundbar and bass**
=> Add DVD Player, Soundbar, TV, Cameo par light, remote

Speakers/Bumpboxx/Bumpboxx.ir
Added Bumpboxx speaker remote that I copied
=> Added Bumpboxx speaker remote

Audio_Receivers/Revo/Revo_Superconnect_BZAWDFB0315H2.ir, Heaters/Hampton Bay/Hampton_Bay_EST-540T-40R.ir
Created ir file for [Revo Superconnect](https://revo-audio.de/products/superconnect/). Recorded from USA version with FCC ID BZAWDFB0315H2.
=> Created Revo_Superconnect_BZAWDFB0315H2.ir

Projectors/SMART/SMART_Projectors.ir
This remote by the company works with many models, so I just gave it a general name instead of putting the models in the file name.
Compatible models are listed in the file.
Feel free to rename it appropriately.
=> Added a SMART projector remote for multiple models

Audio_Video_Receivers/Philips/Philips_BTD2180.ir
Device in question https://www.philips.co.id/c-p/BTD2180_12/micro-music-system
=> Add Philips BTD2180

TVs/Vizio/Vizio_V405-H19.ir
Includes physical remote codes and extra codes not present on the remote.
=> Add Vizio V405-H19 IR file

LED_Lighting/HGomx/HGomx_Saturn_LED_Lamp.ir
i could not ever link this to any other remote in the repo but i'm certain it matches 99% to at least 4
=> Added HGomx_Saturn_LED_Lamp.ir
